function renderHome(){var active=state.clients.filter(isActive),mo=monthKey(),paidCount=active.filter(function(x){return isPaid(x.id,mo)}).length;el('today').textContent=new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'});el('statActive').textContent=active.length;el('statPaid').textContent=paidCount;el('statUnpaid').textContent=active.length-paidCount;el('statWaiting').textContent=state.waiting.length;el('statRevenue').textContent=money(state.payments.filter(function(x){return x.month===mo}).reduce(function(z,x){return z+Number(x.amount||0)},0));var u=active.filter(function(x){return !isPaid(x.id,mo)});el('attention').innerHTML=u.length?u.slice(0,8).map(function(x){return '<div class="card"><div class="row"><div><div class="name">'+esc(x.name)+'</div><div class="muted">'+esc(x.phone||'No phone')+' • '+money(x.fee)+' OMR</div></div><span class="badge unpaid">UNPAID</span></div><button class="whatsapp full" onclick="openWhatsApp(\''+x.id+'\',\'new\')">WhatsApp Message</button></div>'}).join(''):'<div class="card empty">All active clients are paid 🎉</div>'}
function renderSchedule(){el('listViewBtn').classList.toggle('on',scheduleMode==='list');el('tableViewBtn').classList.toggle('on',scheduleMode==='table');el('dayChips').innerHTML=DAYS.map(function(d){return '<span class="badge activebadge">'+d+'</span>'}).join('');var intro='<div class="notice"><b>One shared schedule:</b> every booking below applies to Sunday, Monday and Wednesday.</div>';if(scheduleMode==='list'){el('scheduleBody').innerHTML=intro+TIMES.map(function(t){var bookings=state.bookings.filter(function(b){return b.time===t}).sort(function(a,b){return a.spot-b.spot});return '<div class="card"><div class="slothead"><b>'+t+'</b><span class="muted">'+bookings.length+'/'+CAPACITY+'</span></div>'+(bookings.length?bookings.map(function(b){var x=clientById(b.clientId);if(!x)return'';return '<div class="booking" onclick="openBooking(\''+b.id+'\')"><span><span class="spot">'+b.spot+'</span><b>'+esc(x.name)+'</b></span><span class="badge '+(isPaid(x.id,monthKey())?'paid':'unpaid')+'">'+(isPaid(x.id,monthKey())?'PAID':'UNPAID')+'</span></div>'}).join(''):'<div class="empty">No clients booked</div>')+'<button class="secondary full" onclick="openBookingForm(\''+t+'\')">+ Add client</button></div>'}).join('')}else{var rows='';TIMES.forEach(function(t,idx){var cells='';for(var s=1;s<=CAPACITY;s++){var b=state.bookings.find(function(q){return q.time===t&&q.spot===s}),x=b?clientById(b.clientId):null;if(x){cells+='<td onclick="openBooking(\''+b.id+'\')"><b>'+esc(x.name)+'</b><br><span class="dot '+(isPaid(x.id,monthKey())?'ok':'')+'"></span></td>'}else{cells+='<td><button onclick="openBookingForm(\''+t+'\','+s+')">+</button></td>'}}rows+='<tr><td class="timecell">'+t+'</td>'+cells+'</tr>';if(idx===2)rows+='<tr class="break"><td>BREAK</td><td colspan="'+CAPACITY+'">BREAK</td></tr>'});el('scheduleBody').innerHTML=intro+'<p class="muted">Swipe left/right to see all 9 spots. Green = Paid, Red = Unpaid.</p><div class="ttwrap"><table class="tt"><thead><tr><th></th>'+Array.from({length:CAPACITY},function(_,i){return'<th>'+(i+1)+'</th>'}).join('')+'</tr></thead><tbody>'+rows+'</tbody></table></div>'}}
function openBookingForm(time,preferredSpot){var used=state.bookings.filter(function(x){return x.time===time}),spots=[];for(var i=1;i<=CAPACITY;i++)if(!used.some(function(x){return x.spot===i}))spots.push(i);var alreadyScheduled={};state.bookings.forEach(function(b){alreadyScheduled[b.clientId]=true});var clients=state.clients.filter(isActive).filter(function(x){return !alreadyScheduled[x.id]});openModal('<h3>Add to '+time+'</h3><div class="notice">This booking will apply to <b>Sunday • Monday • Wednesday</b>.</div><div class="field"><label>Client</label><select id="bookingClient"><option value="">Choose client</option>'+clients.map(function(x){return'<option value="'+x.id+'">'+esc(x.name)+'</option>'}).join('')+'</select></div><div class="field"><label>Spot</label><select id="bookingSpot">'+spots.map(function(s){return'<option '+(Number(preferredSpot)===s?'selected':'')+'>'+s+'</option>'}).join('')+'</select></div><div class="actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveBooking(\''+time+'\')">Add to all 3 days</button></div>')}
function saveBooking(time){var cid=el('bookingClient').value;if(!cid)return alert('Choose a client');if(state.bookings.some(function(b){return b.clientId===cid}))return alert('This client is already in the shared weekly schedule.');state.bookings.push({id:uid(),clientId:cid,day:'ALL',time:time,spot:Number(el('bookingSpot').value)});var x=clientById(cid);if(x)x.preferredTime=time;closeModal();saveState()}
function openBooking(id){var b=state.bookings.find(function(x){return x.id===id}),x=b?clientById(b.clientId):null;if(!b||!x)return;openModal('<h3>'+esc(x.name)+'</h3><div class="notice"><b>Sunday • Monday • Wednesday</b><br>'+b.time+' • Spot '+b.spot+'</div><div class="actions"><button class="primary" onclick="openPaymentForm(\''+x.id+'\',\''+monthKey()+'\')">Payment</button><button class="danger" onclick="removeBooking(\''+b.id+'\')">Remove from all 3 days</button></div>')}
function removeBooking(id){var b=state.bookings.find(function(x){return x.id===id});if(b){var c=clientById(b.clientId);if(c)c.preferredTime=''}state.bookings=state.bookings.filter(function(x){return x.id!==id});closeModal();saveState()}
function visibleActiveClients(){var q=(el('clientSearch')&&el('clientSearch').value||'').toLowerCase();return state.clients.filter(isActive).filter(function(x){return (String(x.name||'')+' '+String(x.phone||'')).toLowerCase().indexOf(q)>=0}).sort(sortByRenewalUrgency)}
function toggleBulkSelect(id,checked){if(checked){if(bulkSelected.indexOf(id)<0)bulkSelected.push(id)}else bulkSelected=bulkSelected.filter(function(x){return x!==id});updateBulkToolbar()}
function selectAllVisibleClients(){bulkSelected=visibleActiveClients().map(function(x){return x.id});renderClients()}
function clearBulkSelection(){bulkSelected=[];renderClients()}
function updateBulkToolbar(){var c=el('bulkSelectedCount');if(c)c.textContent=bulkSelected.length;renderBulkQueuePanel()}

