function openClientForm(id){var x=id?clientById(id):null;x=x||{};openModal('<h3>'+(id?'Edit Client':'New Client')+'</h3><div class="field"><label>Name / الاسم</label><input id="clientName" value="'+esc(x.name||'')+'"></div><div class="field"><label>Phone</label><input id="clientPhone" inputmode="tel" value="'+esc(x.phone||'')+'"></div><div class="field"><label>Monthly fee (OMR)</label><input id="clientFee" type="number" step="0.001" value="'+(x.fee!=null?x.fee:75)+'"></div><div class="field"><label>Schedule time / موعد التدريب</label><select id="clientTime"><option value="">Not scheduled</option>'+TIMES.map(function(t){return'<option '+(x.preferredTime===t?'selected':'')+'>'+t+'</option>'}).join('')+'</select></div><div class="notice"><b>Schedule:</b> choosing a time and saving the client adds her automatically to the first available spot in the shared Sunday • Monday • Wednesday timetable.<br><br><b>Membership:</b> duration is 1 calendar month. Choose the first day and the expiry date is calculated automatically.</div><div class="field"><label>Membership start / بداية الاشتراك</label><input id="clientStart" type="date" value="'+(x.membershipStart||'')+'" onchange="autoClientEnd()"></div><div class="field"><label>Extra days / أيام إضافية</label><input id="clientExtraDays" type="number" min="0" step="1" value="'+Math.max(0,Number(x.extraDays||0))+'" oninput="autoClientEnd()"></div><div class="field"><label>Expiry date / تاريخ الانتهاء</label><input id="clientEnd" type="date" value="'+(x.membershipEnd||'')+'" readonly></div><div class="actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveClient(\''+(id||'')+'\')">Save</button></div>')}
function autoClientEnd(){var v=el('clientStart').value,extra=Math.max(0,Number(el('clientExtraDays').value||0));el('clientExtraDays').value=extra;if(v)el('clientEnd').value=membershipEndFromStart(v,extra);else el('clientEnd').value=''}
function saveClient(id){var name=el('clientName').value.trim();if(!name)return alert('Enter client name');var old=id?clientById(id):null;var start=el('clientStart').value,extra=Math.max(0,Number(el('clientExtraDays').value||0)),end=start?membershipEndFromStart(start,extra):'',scheduleTime=el('clientTime').value;var clientId=id||uid(),existingBooking=state.bookings.find(function(b){return b.clientId===clientId}),spot=null;if(scheduleTime){if(existingBooking&&existingBooking.time===scheduleTime)spot=Number(existingBooking.spot);else spot=firstAvailableSpot(scheduleTime,clientId);if(spot===null)return alert(scheduleTime+' is full. Please choose another time.')}var obj={id:clientId,name:name,phone:el('clientPhone').value.trim(),fee:Number(el('clientFee').value||0),preferredTime:scheduleTime,membershipStart:start,membershipEnd:end,extraDays:extra,active:old?old.active!==false:true,status:old&&old.status?old.status:'active'};if(old){Object.keys(old).forEach(function(k){if(obj[k]===undefined)obj[k]=old[k]});state.clients=state.clients.map(function(x){return x.id===id?obj:x})}else state.clients.push(obj);state.bookings=state.bookings.filter(function(b){return b.clientId!==clientId});if(scheduleTime)state.bookings.push({id:existingBooking?existingBooking.id:uid(),clientId:clientId,day:'ALL',time:scheduleTime,spot:spot});closeModal();saveState()}
function archiveClient(id){var x=clientById(id);if(!x)return;if(!confirm('Archive '+x.name+'?'))return;x.active=false;x.status='archived';state.bookings=state.bookings.filter(function(b){return b.clientId!==id});saveState()}
function restoreClient(id){var x=clientById(id);if(!x)return;x.active=true;x.status='active';saveState()}
function moveToWaiting(id){var x=clientById(id);if(!x)return;if(!state.waiting.some(function(w){return w.clientId===id}))state.waiting.push({id:uid(),clientId:id,name:x.name,phone:x.phone||'',time:x.preferredTime||''});x.active=false;x.status='waiting';state.bookings=state.bookings.filter(function(b){return b.clientId!==id});saveState()}
function renderPayments(){el('paymentMonth').value=selectedPaymentMonth;document.querySelectorAll('[data-payfilter]').forEach(function(b){b.classList.toggle('on',b.dataset.payfilter===paymentFilter);b.onclick=function(){paymentFilter=b.dataset.payfilter;renderPayments()}});var list=state.clients.filter(isActive);if(paymentFilter==='paid')list=list.filter(function(x){return isPaid(x.id,selectedPaymentMonth)});if(paymentFilter==='unpaid')list=list.filter(function(x){return !isPaid(x.id,selectedPaymentMonth)});el('paymentList').innerHTML=list.length?list.map(function(x){var p=paymentFor(x.id,selectedPaymentMonth);return '<div class="card"><div class="row"><div><div class="name">'+esc(x.name)+'</div><div class="muted">'+(p?money(p.amount)+' OMR • '+esc(p.method):'Due '+money(x.fee)+' OMR')+'</div></div><button class="'+(p?'secondary':'primary')+'" onclick="openPaymentForm(\''+x.id+'\',\''+selectedPaymentMonth+'\')">'+(p?'View':'Mark Paid')+'</button></div><button class="whatsapp full" onclick="openWhatsApp(\''+x.id+'\',\''+(x.membershipEnd?'renew':'new')+'\')">WhatsApp</button></div>'}).join(''):'<div class="card empty">No clients in this filter</div>'}
function openPaymentForm(cid,month){var x=clientById(cid),p=paymentFor(cid,month);if(!x)return;openModal('<h3>'+esc(x.name)+'</h3><div class="notice">'+month+'</div><div class="field"><label>Amount OMR</label><input id="payAmount" type="number" step="0.001" value="'+(p?p.amount:x.fee)+'"></div><div class="field"><label>Method</label><select id="payMethod">'+['Cash','Bank Transfer','Card','Other'].map(function(v){return'<option '+(p&&p.method===v?'selected':'')+'>'+v+'</option>'}).join('')+'</select></div><div class="actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="savePayment(\''+cid+'\',\''+month+'\',\''+(p?p.id:'')+'\')">Save</button></div>'+(p?'<button class="danger full" onclick="removePayment(\''+p.id+'\')">Mark Unpaid</button>':'') )}
function savePayment(cid,month,id){var obj={id:id||uid(),clientId:cid,month:month,amount:Number(el('payAmount').value||0),method:el('payMethod').value,date:todayISO()};if(id)state.payments=state.payments.map(function(x){return x.id===id?obj:x});else state.payments.push(obj);closeModal();saveState()}
function removePayment(id){state.payments=state.payments.filter(function(x){return x.id!==id});closeModal();saveState()}
function renderWaiting(){el('waitingList').innerHTML=state.waiting.length?state.waiting.map(function(w){return '<div class="card"><div class="row"><div><div class="name">'+esc(w.name)+'</div><div class="muted">'+esc(w.phone||'')+(w.time?' • '+esc(w.time):'')+'</div></div><span class="badge neutralbadge">WAITING</span></div><div class="actions"><button class="primary" onclick="activateWaiting(\''+w.id+'\')">Move to Clients</button><button class="danger" onclick="removeWaiting(\''+w.id+'\')">Remove</button></div></div>'}).join(''):'<div class="card empty">Waiting list is empty</div>'}
function openWaitingForm(){openModal('<h3>Add to Waiting List</h3><input id="waitingName" placeholder="Name"><input id="waitingPhone" placeholder="Phone" inputmode="tel"><select id="waitingTime"><option value="">Flexible</option>'+TIMES.map(function(t){return'<option>'+t+'</option>'}).join('')+'</select><div class="actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveWaiting()">Save</button></div>')}
function saveWaiting(){var n=el('waitingName').value.trim();if(!n)return alert('Enter name');state.waiting.push({id:uid(),name:n,phone:el('waitingPhone').value.trim(),time:el('waitingTime').value});closeModal();saveState()}
function activateWaiting(id){var w=state.waiting.find(function(x){return x.id===id});if(!w)return;var x=w.clientId?clientById(w.clientId):null;if(x){x.active=true;x.status='active'}else state.clients.push({id:uid(),name:w.name,phone:w.phone||'',fee:75,preferredTime:w.time||'',membershipStart:'',membershipEnd:'',extraDays:0,active:true,status:'active'});state.waiting=state.waiting.filter(function(x){return x.id!==id});saveState()}
function removeWaiting(id){state.waiting=state.waiting.filter(function(x){return x.id!==id});saveState()}

