function renderReport(){el('reportMonth').value=selectedReportMonth;var payments=state.payments.filter(function(x){return x.month===selectedReportMonth}),expenses=state.expenses.filter(function(x){return x.month===selectedReportMonth}),active=state.clients.filter(isActive),revenue=payments.reduce(function(z,x){return z+Number(x.amount||0)},0),exp=expenses.reduce(function(z,x){return z+Number(x.amount||0)},0),net=revenue-exp,expected=active.reduce(function(z,x){return z+Number(x.fee||0)},0),outstanding=active.filter(function(x){return !isPaid(x.id,selectedReportMonth)}).reduce(function(z,x){return z+Number(x.fee||0)},0),paidClients=active.filter(function(x){return isPaid(x.id,selectedReportMonth)}).length;el('reportStats').innerHTML='<div class="stat"><span>Revenue</span><b>'+money(revenue)+' OMR</b></div><div class="stat"><span>Expenses</span><b>'+money(exp)+' OMR</b></div><div class="stat"><span>Net Profit</span><b>'+money(net)+' OMR</b></div><div class="stat"><span>Profit Margin</span><b>'+(revenue?(net/revenue*100).toFixed(1):'0.0')+'%</b></div><div class="stat"><span>Expected Income</span><b>'+money(expected)+' OMR</b></div><div class="stat"><span>Outstanding</span><b>'+money(outstanding)+' OMR</b></div><div class="stat"><span>Paid Clients</span><b>'+paidClients+'</b></div><div class="stat"><span>Unpaid Clients</span><b>'+(active.length-paidClients)+'</b></div>';el('reportPayments').innerHTML=payments.length?payments.map(function(p){var x=clientById(p.clientId);return '<div class="detail"><div><b>'+esc(x?x.name:'Unknown')+'</b><div class="muted">'+esc(p.date||'')+' • '+esc(p.method||'')+'</div></div><span class="amount">'+money(p.amount)+' OMR</span></div>'}).join(''):'<div class="empty">No payments</div>';el('reportExpenses').innerHTML=expenses.length?expenses.map(function(x){return '<div class="detail"><div><b>'+esc(x.category)+'</b><div class="muted">'+esc(x.date||'')+(x.notes?' • '+esc(x.notes):'')+'</div></div><span class="amount">'+money(x.amount)+' OMR</span></div>'}).join(''):'<div class="empty">No expenses</div>'}
function openExpenseForm(){openModal('<h3>Add Expense</h3><input id="expenseMonth" type="month" value="'+selectedReportMonth+'"><select id="expenseCategory">'+['Rent','Trainer / Salary','Equipment','Utilities','Marketing','Maintenance','Supplies','Other'].map(function(v){return'<option>'+v+'</option>'}).join('')+'</select><input id="expenseAmount" type="number" step="0.001" placeholder="Amount OMR"><input id="expenseNotes" placeholder="Notes"><div class="actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveExpense()">Save</button></div>')}
function saveExpense(){state.expenses.push({id:uid(),month:el('expenseMonth').value||selectedReportMonth,category:el('expenseCategory').value,amount:Number(el('expenseAmount').value||0),date:todayISO(),notes:el('expenseNotes').value.trim()});selectedReportMonth=el('expenseMonth').value||selectedReportMonth;closeModal();saveState()}
function applyTemplate(template,x,start,end){return String(template||'').replace(/\{name\}/g,x.name||'').replace(/\{start\}/g,formatDate(start)).replace(/\{end\}/g,formatDate(end)).replace(/\{fee\}/g,money(x.fee)).replace(/\{time\}/g,x.preferredTime||'Flexible')}
function suggestedStart(x,type){if(type==='renew'&&x.membershipEnd)return dateAddDays(x.membershipEnd,1);return x.membershipStart||todayISO()}
function openWhatsApp(cid,type){var x=clientById(cid);if(!x)return;var ph=normalizePhone(x.phone);if(!ph)return alert('Please add a phone number first.');type=type==='renew'?'renew':'new';var start=suggestedStart(x,type),extra=type==='renew'?0:Math.max(0,Number(x.extraDays||0)),end=membershipEndFromStart(start,extra);renderWhatsAppModal(cid,type,start,end,extra)}
function renderWhatsAppModal(cid,type,start,end,extra){var x=clientById(cid);extra=Math.max(0,Number(extra||0));var template=type==='renew'?state.settings.waRenew:state.settings.waNew;var msg=applyTemplate(template,x,start,end);openModal('<h3>WhatsApp Message</h3><div class="msgtype"><button class="'+(type==='new'?'on':'')+'" onclick="switchWAType(\''+cid+'\',\'new\')">New Membership</button><button class="'+(type==='renew'?'on':'')+'" onclick="switchWAType(\''+cid+'\',\'renew\')">Renewal</button></div><input id="waClientId" type="hidden" value="'+cid+'"><input id="waType" type="hidden" value="'+type+'"><div class="notice">1-month subscription. Add extra days below when needed.</div><div class="field"><label>Start date / بداية الاشتراك</label><input id="waStart" type="date" value="'+start+'" onchange="waDatesChanged()"></div><div class="field"><label>Extra days / أيام إضافية</label><input id="waExtraDays" type="number" min="0" step="1" value="'+extra+'" oninput="waDatesChanged()"></div><div class="field"><label>Expiry date / تاريخ الانتهاء</label><input id="waEnd" type="date" value="'+end+'" readonly></div><div class="field"><label>Message / الرسالة</label><textarea id="waMessage" class="preview">'+esc(msg)+'</textarea></div><p class="help">You can edit this message before sending. The saved template will not change unless you edit it in Settings.</p><div class="actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="secondary" onclick="copyWhatsAppMessage()">Copy Message / نسخ الرسالة</button><button class="whatsapp" onclick="sendWhatsApp()">Save & Open WhatsApp</button></div>')}
function switchWAType(cid,type){var x=clientById(cid),start=suggestedStart(x,type),extra=type==='renew'?0:Math.max(0,Number(x.extraDays||0)),end=membershipEndFromStart(start,extra);renderWhatsAppModal(cid,type,start,end,extra)}
function waDatesChanged(){var start=el('waStart').value,extra=Math.max(0,Number(el('waExtraDays').value||0));el('waExtraDays').value=extra;if(start)el('waEnd').value=membershipEndFromStart(start,extra);else el('waEnd').value='';refreshWAMessage()}
function refreshWAMessage(){var cid=el('waClientId').value,type=el('waType').value,x=clientById(cid);if(!x)return;var template=type==='renew'?state.settings.waRenew:state.settings.waNew;el('waMessage').value=applyTemplate(template,x,el('waStart').value,el('waEnd').value)}
function sendWhatsApp(){var cid=el('waClientId').value,type=el('waType').value,x=clientById(cid);if(!x)return;var start=el('waStart').value,extra=Math.max(0,Number(el('waExtraDays').value||0)),end=start?membershipEndFromStart(start,extra):'',msg=el('waMessage').value.trim(),ph=normalizePhone(x.phone);if(!start||!end)return alert('Please select a start date.');if(!msg)return alert('Please enter a message.');x.membershipStart=start;x.membershipEnd=end;x.extraDays=extra;x.lastWhatsAppType=type;x.lastWhatsAppDate=todayISO();localStorage.setItem(KEY,JSON.stringify(state));closeModal();renderAll();window.location.href='https://wa.me/'+ph+'?text='+encodeURIComponent(msg)}

function fallbackCopyText(text){var ta=document.createElement('textarea');ta.value=text;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.focus();ta.select();ta.setSelectionRange(0,99999);var ok=false;try{ok=document.execCommand('copy')}catch(e){}document.body.removeChild(ta);alert(ok?'تم نسخ الرسالة ✅':'تعذر النسخ، يمكنك تحديد النص ونسخه يدويًا.')}
function copyText(text){if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(text).then(function(){alert('تم نسخ الرسالة ✅')}).catch(function(){fallbackCopyText(text)})}else fallbackCopyText(text)}
function copyWhatsAppMessage(){var m=el('waMessage');if(m)copyText(m.value)}
function copyCurrentBulkWhatsApp(){var ids=bulkPendingIds();if(!ids.length)return;var x=clientById(ids[0]);if(!x)return;copyText(bulkMessageFor(x))}
function saveTemplates(){state.settings.waNew=el('newTemplate').value||DEFAULT_NEW;state.settings.waRenew=el('renewTemplate').value||DEFAULT_RENEW;localStorage.setItem(KEY,JSON.stringify(state));alert('WhatsApp templates saved')}
function renderSettings(){el('newTemplate').value=state.settings.waNew;el('renewTemplate').value=state.settings.waRenew}
